defaults: &defaults
  region: <%= ENV['AWS_REGION'] %>

  us-east-1:
    vpc_limit: 10
    instance_limit: 60

  us-west-1:
    vpc_limit: 5
    instance_limit: 20

  us-west-2:
    vpc_limit: 5
    instance_limit: 20

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
