
development:
  adapter: postgresql
  encoding: unicode
  pool: 50
  timeout: 5000
  host: localhost
  database: edurange_development
  # In development you must create this user in postgresql. This can be done by:
  # CREATE USER edurange WITH PASSWORD 'edurange_rocks!' CREATEDB;
  username: edurange
  password: 'edurange_rocks!'

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool: 50
  timeout: 5000
  # The DATABASE_URL environment variables supplies host, port, database, username, password, etc.
