
development:
#  adapter: sqlite3
#  pool: 5
#  timeout: 5000
#  database: db/development.sqlite3
  adapter: postgresql
  encoding: unicode
  database: edurange_development
  pool: 5
  timeout: 5000



test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: edurange_production
  pool: 5
  timeout: 5000

